### ISSUE TITLE
Craft 5

### ISSUE THREAD

**Issue by jonleverrier** [scandella/ScandellaSqueeze#1]
Appreciate this repo was an unofficial port to Craft 4, but is there any plans to update it to Craft 5?

**Comment by scandella** [comment]
Yes definitely.
I'm just started a new Craft 5 project, so I'll give a try and let you know.

**Comment by jonleverrier** [comment]
Did you get anywhere with the v5 port?

**Comment by scandella** [comment]
@jonleverrier 
Jon, [I submitted the plugin to Verbb's support offering](https://verbb.io/craft-4). If the application is accepted, we'll need to vote for it to be supported.

**Comment by scandella** [comment]
@jonleverrier 
Jon, [the plugin is open to vote now](https://verbb.io/craft-4).
